name: proyecto
description: Aplicación de aprendizaje de idiomas
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.2
  provider: ^6.0.5
  image_picker: ^0.8.4+4
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.9
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.17.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/