// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuCUKemW_1MCjloe5wFPdRLZCO8nwjjak',
    appId: '1:8549784372:web:c6ad3b2c55b674c5b4e361',
    messagingSenderId: '8549784372',
    projectId: 'appingles-3106c',
    authDomain: 'appingles-3106c.firebaseapp.com',
    storageBucket: 'appingles-3106c.firebasestorage.app',
    measurementId: 'G-70EP0WSMHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWKdgzQPQfGYH7JaCn6qEfCWAGiT0516w',
    appId: '1:8549784372:android:4c55e5f79f1a317ab4e361',
    messagingSenderId: '8549784372',
    projectId: 'appingles-3106c',
    storageBucket: 'appingles-3106c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg4aWHKRlz_Jx7UomuctHsH6_UTDhkR9o',
    appId: '1:8549784372:ios:a901a1befe7f7755b4e361',
    messagingSenderId: '8549784372',
    projectId: 'appingles-3106c',
    storageBucket: 'appingles-3106c.firebasestorage.app',
    iosBundleId: 'com.example.proyecto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg4aWHKRlz_Jx7UomuctHsH6_UTDhkR9o',
    appId: '1:8549784372:ios:a901a1befe7f7755b4e361',
    messagingSenderId: '8549784372',
    projectId: 'appingles-3106c',
    storageBucket: 'appingles-3106c.firebasestorage.app',
    iosBundleId: 'com.example.proyecto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuCUKemW_1MCjloe5wFPdRLZCO8nwjjak',
    appId: '1:8549784372:web:cdc66584388baf10b4e361',
    messagingSenderId: '8549784372',
    projectId: 'appingles-3106c',
    authDomain: 'appingles-3106c.firebaseapp.com',
    storageBucket: 'appingles-3106c.firebasestorage.app',
    measurementId: 'G-7C1FGRQMWV',
  );
}
